---
#- name: add release key
#  apt_key:
#    url: https://download.ceph.com/keys/release.asc
#    state: present
#- name: add Ceph packages to repository
#  apt_repository:
#    repo: deb https://download.ceph.com/debian {{ ansible_lsb.codename|lower }} main
#    state: present
#    filename: '/etc/apt/sources.list.d/ceph.list'
#- name: Update repositories cache and install "ceph-deploy" package
#  apt:
#    name: ceph-deploy
#    update_cache: yes
#- name: add release key
#  rpm_key:
#    key: https://download.ceph.com/keys/release.asc
#    state: present

- name: add Ceph yum repository
  yum_repository:
    name: ceph.repo
    description: "Ceph.Repo"
    file: ceph.repo
    baseurl: https://download.ceph.com/ceph/rpm-nautilus/el7/$basearch
    enabled: yes
    gpgkey: https://download.ceph.com/keys/release.asc
    gpgcheck: yes

- name: Update repository cache and install ceph-deploy package
  yum:
    name: ceph-deploy
    update_cache: yes
    state: latest