---
- name: install Docker
  hosts: osd
  roles:
    - 10-docker-installation

- name: init Docker swarm
  hosts: node1
  roles:
    - 11-docker-swarm-init

- name: add managers
  hosts: node2, node3
  roles:
    - 12-docker-swarm-add-manager