---
- name: common configuration
  hosts: all
  roles:
    - 01-create-sudo-user
    - 02-install-modules
    - 03-configure-hosts-file

- name: setup admin node
  become: yes
  become_user: sense
  hosts: admin
  roles:
    - 04-admin-configure

- name: copy admin key to nodes
  become: yes
  become_user: sense
  hosts: mon, osd
  roles:
    - 05-admin-copy-keys

#- name: ceph-deploy setup
#  hosts: admin
#  roles:
#    - 06-ceph-deploy-setup
#
#- name: deploy cluster
#  become: true
#  become_method: su
#  become_user: sense
#  become_flags: '-'
#  hosts: admin
#  roles:
#    - 07-deploy-ceph-cluster
#
#- name: install REX-Ray
#  hosts: osd
#  roles:
#    - rex-ray-installation
#    - rex-ray-configuration

- name: install Docker
  hosts: osd
  roles:
    - 10-docker-installation

- name: init Docker swarm
  hosts: ceph1
  roles:
    - 11-docker-swarm-init

- name: add managers
  hosts: ceph2, ceph3
  roles:
    - 12-docker-swarm-add-manager