---
- name: leave swarm
  shell: docker swarm leave -f
  ignore_errors: true

- name: remove Docker
  yum: name="docker-ce" state=latest update_cache=yes state=absent
  tags: docker

- name: Remove repository from a specific repo file
  yum_repository:
    name: docker-ce
    file: docker-ce.repos
    state: absent