#---
#- name: install Docker dependencies
#  apt: name={{ item }} state=latest update_cache=yes
#  with_items:
#    - apt-transport-https
#    - ca-certificates
#    - curl
#    - software-properties-common
#  tags: docker
#
#- name: add Docker key
#  apt_key:
#    url: https://download.docker.com/linux/ubuntu/gpg
#    state: present
#  tags: docker
#
#- name: add Docker packages to repository
#  apt_repository:
#    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower }} stable
#  tags: docker
#
#- name: install Docker
#  apt: name="docker-ce" state=latest update_cache=yes
#  tags: docker

---
#- name: install Docker dependencies
#  yum: name={{ item }} state=latest update_cache=yes state=present
#  with_items:
#    - apt-transport-https
#    - ca-certificates
#    - curl
#    - software-properties-common
#  tags: docker

- name: add Docker key
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present
  tags: docker

- name: add Docker packages to repository
  yum_repository:
    name: docker_repo
    description: "docker yum repository"
    file: docker_ce.repo
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    enabled: yes
  tags: docker

- name: install Docker
  yum: name="docker-ce" state=latest update_cache=yes state=present
  tags: docker

- name: "add docker group"
  group: name=docker state=present

- name: "add ubuntu to docker group"
  user: name=sense groups=docker append=yes

- name: "restart docker service"
  service: name=docker state=started

- name: "get docker info"
  shell: docker info
  register: docker_info
  changed_when: false