---
- name: create sudo user
  user:
    name: sense
    shell: /bin/bash
    append: yes
    comment: "sense nologin User"
    state: present
  become: true
- name: set password less access for sense
  lineinfile:
    path: /etc/sudoers.d/sense
    line: 'sense ALL=(ALL) NOPASSWD: ALL'
    state: present
    mode: 0440
    create: yes
    validate: 'visudo -cf %s'