---
- name: create sudo user
  user: name=sense
    groups=sudo
    shell=/bin/bash
    generate_ssh_key=no
    state=present

- name: set password less access for sense
  copy: src=sudoers
    dest=/etc/sudoers.d
    mode=0440