---
- name: create sudo user
  user: name=sense
    groups=sudo
    shell=/bin/bash
    generate_ssh_key=no
    state=present

- name: set password less access for sense
  lineinfile:
    path: /etc/sudoers.d/ansibleuser
    line: 'ansibleuser ALL=(ALL) NOPASSWD: ALL'
    state: present
    mode: 0440
    create: yes
    validate: 'visudo -cf %s'