---
- name: create sudo user
  user:
    name: sense
    shell: /bin/bash
    generate_ssh_key: no
    state=: present
    groups: sense

- name: set password less access for sense
  lineinfile:
    path: /etc/sudoers.d/ansibleuser
    line: 'ansibleuser ALL=(ALL) NOPASSWD: ALL'
    state: present
    mode: 0440
    create: yes
    validate: 'visudo -cf %s'