---
- name: register swarm status
  shell: docker node ls
  register: swarm_status
  ignore_errors: true
  tags: swarm

- name: add managers
  shell: "docker swarm join --token {{ hostvars['ceph1']['manager_token']['stdout'] }} {{ hostvars['ceph1']['ansible_default_ipv4']['address'] }}:2377"
  when: swarm_status.rc != 0
  tags: swarm
