---
- name: Generate SSH keys
  shell: ssh-keygen -b 2048 -f /home/sense/.ssh/id_rsa -t rsa -q -N ""
  args:
    creates: /home/sense/.ssh/id_rsa
- name: copy public key locally
  fetch:
    src: /home/sense/.ssh/id_rsa.pub
    dest: /tmp/
    flat: yes
- name: copy ssh configuration
  copy:
    src: ssh_config
    dest: /home/sense/.ssh/config
    mode: 0644
- name: empty known_hosts
  file:
    state: absent
    path: ~/.ssh/known_hosts
- name: run ssh-keyscan to add keys to known_hosts
  shell: "ssh-keyscan {{ item }} >> ~/.ssh/known_hosts"
  with_items:
    - "node1"
    - "node2"
    - "node3"
